services:
  centralizegg__trn_db:
    image: timescale/timescaledb-ha:pg15-all
    restart: always
    environment:
      POSTGRES_USER: centralizegg
      POSTGRES_PASSWORD: centralizegg_secret
      POSTGRES_DB: centralizegg_db
    volumes:
      - ./deploy_centralizegg/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U centralizegg -d centralizegg_db" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - centralizegg-net

  centralizegg_app:
    build: .
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - /var/run/libvirt/libvirt-sock:/var/run/libvirt/libvirt-sock
      - ~/.ssh:/root/.ssh:ro
    environment:
      DB_HOST: centralizegg__trn_db
      DB_PORT: 5432
      DB_USER: centralizegg
      DB_PASS: centralizegg_secret
      DB_NAME: centralizegg_db
      LIBVIRT_SOCK: /var/run/libvirt/libvirt-sock
    depends_on:
      centralizegg__trn_db:
        condition: service_healthy
    networks:
      - centralizegg-net

networks:
  centralizegg-net:
    driver: bridge
