name: Build Scan Push - DockerHub

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

permissions:
  contents: read
  security-events: write

jobs:
  deploy:
    uses: grs89/github-template/.github/workflows/docker-publish.yml@v2
    secrets:
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_REPO: ${{ secrets.DOCKERHUB_REPO }}
