name: Build Scan Push - DockerHub 

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch: 

jobs:
  deploy:
    uses: grs89/github-template/.github/workflows/docker-publish.yml@v1
    secrets:
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
